// lazyload config

var jp_config = {
  easyPieChart:   [ '/Scripts/charts/easypiechart/jquery.easy-pie-chart.js' ],
  sparkline:      [ '/Scripts/charts/sparkline/jquery.sparkline.min.js' ],
  plot:           [ '/Scripts/charts/flot/jquery.flot.min.js', 
                    '/Scripts/charts/flot/jquery.flot.resize.js',
                    '/Scripts/charts/flot/jquery.flot.tooltip.min.js',
                    '/Scripts/charts/flot/jquery.flot.spline.js',
                    '/Scripts/charts/flot/jquery.flot.orderBars.js',
                    '/Scripts/charts/flot/jquery.flot.pie.min.js' ],
  slimScroll:     [ '/Scripts/slimscroll/jquery.slimscroll.min.js' ],
  vectorMap:      [ '/Scripts/jvectormap/jquery-jvectormap.min.js', 
                    '/Scripts/jvectormap/jquery-jvectormap-world-mill-en.js',
                    '/Scripts/jvectormap/jquery-jvectormap-us-aea-en.js',
                    '/Scripts/jvectormap/jquery-jvectormap.css' ],
  sortable:       [ '/Scripts/sortable/jquery.sortable.js' ],
  nestable:       [ '/Scripts/nestable/jquery.nestable.js',
                      '/Scripts/nestable/nestable.css' ],
  filestyle:      [ '/Scripts/file/bootstrap-filestyle.min.js' ],
  slider:         [ '/Scripts/slider/bootstrap-slider.js',
                      '/Scripts/slider/slider.css' ],
  chosen:         [ '/Scripts/chosen/chosen.jquery.min.js',
                      '/Scripts/chosen/chosen.css' ],
  TouchSpin:      [ '/Scripts/spinner/jquery.bootstrap-touchspin.min.js',
                      '/Scripts/spinner/jquery.bootstrap-touchspin.css' ],
  wysiwyg:        [ '/Scripts/wysiwyg/bootstrap-wysiwyg.js',
                      '/Scripts/wysiwyg/jquery.hotkeys.js' ],
  dataTable:      [ '/Scripts/datatables/jquery.dataTables.min.js',
                      '/Scripts/datatables/dataTables.bootstrap.js',
                      '/Scripts/datatables/dataTables.bootstrap.css' ],
  footable:       [ '/Scripts/footable/footable.all.min.js',
                      '/Scripts/footable/footable.core.css' ]
};